import { Injectable, Inject, NotFoundException } from '@nestjs/common';
import { DATABASE_CONNECTION } from '../../database/database.module';
import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import * as schema from '../../database/schema';
import { CreateReportDto } from './dto/create-report.dto';
import { CreateReactionDto, ReactionType } from './dto/create-reaction.dto';
import { UpdateReportDto } from './dto/update-report.dto';
import { GetReportsFilterDto, SortOption } from './dto/get-reports-filter.dto';
import { eq, and, sql, desc } from 'drizzle-orm';
import { ConflictException } from '@nestjs/common';

@Injectable()
export class ReportsService {
  constructor(
    @Inject(DATABASE_CONNECTION)
    private readonly db: NodePgDatabase<typeof schema>,
  ) {}

  async create(createReportDto: CreateReportDto, reporterId: string) {
    const { media, ...reportData } = createReportDto;

    return await this.db.transaction(async (tx) => {
      // 1. Create the report
      const [report] = await tx
        .insert(schema.reports)
        .values({
          ...reportData,
          reporterId,
          status: 'published', // Set initial status based on requirements
          confidenceScore: 0, // Initial confidence score
          // Timestamp is auto-generated by the database default value
        })
        .returning();

      // 2. Prepare media data for insertion
      const mediaValues = media.map((mediaItem) => ({
        reportId: report.id,
        type: mediaItem.type,
        url: mediaItem.url,
        duration: mediaItem.duration,
        processingStatus: 'pending' as const, // Prepare for async processing
      }));

      // 3. Insert media records
      const insertedMedia = await tx
        .insert(schema.media)
        .values(mediaValues)
        .returning();

      // Return the created report including its media
      return {
        ...report,
        media: insertedMedia,
      };
    });
  }

  async findAll(filters: GetReportsFilterDto) {
    const {
      city,
      area,
      category,
      urgency,
      status,
      search,
      sort,
      page = 1,
      limit = 20,
    } = filters;
    const offset = (page - 1) * limit;

    const queryFilters = [];

    if (city) queryFilters.push(eq(schema.reports.cityId, city));
    if (area) queryFilters.push(eq(schema.reports.areaId, area));
    if (category) queryFilters.push(eq(schema.reports.categoryId, category));
    if (urgency)
      queryFilters.push(
        eq(
          schema.reports.urgencyLevel,
          urgency as 'info' | 'warning' | 'critical',
        ),
      );
    if (status)
      queryFilters.push(
        eq(
          schema.reports.status,
          status as 'published' | 'under_review' | 'removed' | 'verified',
        ),
      );

    // GIN Full-Text Search
    if (search) {
      const searchTerms = search.trim().split(' ').join(' | '); // Convert to tsquery syntax
      queryFilters.push(
        sql`${schema.reports.searchVector} @@ to_tsquery('english', ${searchTerms})`,
      );
    }

    let orderByClause;
    if (sort === SortOption.URGENT) {
      // SQL mapping: critical > warning > info
      orderByClause = sql`
        CASE ${schema.reports.urgencyLevel}
          WHEN 'critical' THEN 1
          WHEN 'warning' THEN 2
          WHEN 'info' THEN 3
          ELSE 4
        END ASC, ${schema.reports.createdAt} DESC
       `;
    } else if (sort === SortOption.CONFIDENCE) {
      orderByClause = desc(schema.reports.confidenceScore);
    } else {
      // Default SortOption.RECENT
      orderByClause = desc(schema.reports.createdAt);
    }

    const data = await this.db.query.reports.findMany({
      where: queryFilters.length > 0 ? and(...queryFilters) : undefined,
      orderBy: orderByClause,
      limit,
      offset,
      with: {
        category: true,
        city: true,
        area: true,
        reporter: {
          columns: {
            id: true,
            displayName: true,
            trustScore: true,
          },
        },
        media: true,
      },
    });

    return {
      data,
      meta: {
        page,
        limit,
      },
    };
  }

  async findOne(id: string) {
    const report = await this.db.query.reports.findFirst({
      where: eq(schema.reports.id, id),
      with: {
        category: true,
        city: true,
        area: true,
        media: true,
        reporter: {
          columns: {
            id: true,
            displayName: true,
            trustScore: true,
          },
        },
      },
    });

    if (!report) {
      throw new NotFoundException(`Report with ID ${id} not found`);
    }

    return report;
  }

  async update(id: string, updateReportDto: UpdateReportDto) {
    const [updatedReport] = await this.db
      .update(schema.reports)
      .set({
        ...updateReportDto,
        updatedAt: new Date(),
      })
      .where(eq(schema.reports.id, id))
      .returning();

    if (!updatedReport) {
      throw new NotFoundException(`Report with ID ${id} not found`);
    }

    return updatedReport;
  }

  async reactToReport(
    reportId: string,
    userId: string,
    reactionDto: CreateReactionDto,
  ) {
    const isFake = reactionDto.vote === ReactionType.FAKE;

    try {
      return await this.db.transaction(async (tx) => {
        // 1. Check if report exists
        const report = await tx.query.reports.findFirst({
          where: eq(schema.reports.id, reportId),
          with: {
            reporter: {
              columns: {
                id: true,
                trustScore: true,
              },
            },
          },
        });

        if (!report) {
          throw new NotFoundException(`Report with ID ${reportId} not found`);
        }

        // 2. Insert reaction FIRST securely
        // Leverages Postgres unique_violation immediately to prevent TOCTOU duplicate races
        try {
          await tx.insert(schema.reactions).values({
            reportId,
            userId,
            isFake,
          });
        } catch (error: any) {
          if (error.code === '23505') {
            throw new ConflictException(
              'User has already reacted to this report.',
            );
          }
          throw error;
        }

        // 4. Calculate new confidence score dynamically
        let confidenceDelta = isFake ? -5 : 5; // Base impact

        // Factor in Reporter Trust Score
        const reporterTrustScore = report.reporter?.trustScore || 50;
        if (reporterTrustScore > 80) {
          confidenceDelta += isFake ? -2 : 2; // High trust users have more stable initial score
        } else if (reporterTrustScore < 30) {
          confidenceDelta += isFake ? -10 : 0; // Low trust users drop very fast on fake votes
        }

        // 5. Update Report Atomically (Prevents Read-Modify-Write Race Conditions)
        const [updatedReport] = await tx
          .update(schema.reports)
          .set({
            reportsVotes: sql`${schema.reports.reportsVotes} + 1`,
            confidenceScore: sql`${schema.reports.confidenceScore} + ${confidenceDelta}`,
            updatedAt: new Date(),
          })
          .where(eq(schema.reports.id, reportId))
          .returning();

        const newConfidenceScore = updatedReport.confidenceScore;
        const oldConfidenceScore = report.confidenceScore;

        // 6. Conditionally update reporter's trustScore ONLY when crossing the thresholds
        if (
          oldConfidenceScore >= -50 &&
          newConfidenceScore < -50 &&
          reporterTrustScore > 0
        ) {
          await tx
            .update(schema.users)
            .set({
              trustScore: sql`GREATEST(${schema.users.trustScore} - 10, 0)`,
            })
            .where(eq(schema.users.id, report.reporterId));
        } else if (
          oldConfidenceScore <= 50 &&
          newConfidenceScore > 50 &&
          reporterTrustScore < 100
        ) {
          await tx
            .update(schema.users)
            .set({
              trustScore: sql`LEAST(${schema.users.trustScore} + 1, 100)`,
            })
            .where(eq(schema.users.id, report.reporterId));
        }

        return {
          message: 'Reaction submitted successfully',
          newConfidenceScore,
        };
      });
    } catch (error: unknown) {
      if (
        error instanceof ConflictException ||
        error instanceof NotFoundException
      ) {
        throw error;
      }

      // Handle potential Drizzle/Postgres unique constraint throws just in case
      // standard code for Postgres unique violation is '23505'
      if ((error as any)?.code === '23505') {
        throw new ConflictException('User has already reacted to this report.');
      }

      throw error;
    }
  }

  async remove(id: string) {
    const [deletedReport] = await this.db
      .delete(schema.reports)
      .where(eq(schema.reports.id, id))
      .returning({ id: schema.reports.id });

    if (!deletedReport) {
      throw new NotFoundException(`Report with ID ${id} not found`);
    }

    return { message: 'Report deleted successfully', id: deletedReport.id };
  }
}
